### ISSUE TITLE
ValueError: Unexpected WORD token at 1:13, expecting l-paren, got 'hook'

### ISSUE THREAD

**Issue by qibint** [aharrison24/cmake-format-pre-commit#1] opened 2019-10-08 19:37 UTC
Hi, @aharrison24. 
Thank you for your effort to integrate the cmake-format with the pre-commit hooks. But as I installed the cmake-format from your this separate repo, I basically found two issues. 

One of them is in the .pre-commit-hooks.yaml file, if I use the cmake type, pre-commit will not find the text files. 
The second issue is after I updated to types: [text], the pre-commit try-repo command works, but when I do a real git commit, an error shows:

$git commit -m "Test pre-commit hooks"
cmake-format.............................................................Failed
hookid: cmake-format

While processing cmake-format-pre-commit/README.md
Traceback (most recent call last):
  File "/Users/xx/.cache/pre-commit/repofxy8xq7j/py_env-python3.7/bin/cmake-format", line 10, in <module>
    sys.exit(main())
  File "/Users/xx/.cache/pre-commit/repofxy8xq7j/py_env-python3.7/lib/python3.7/site-packages/cmake_format/__main__.py", line 498, in main
    outtext = process_file(cfg, intext, args.dump)
  File "/Users/xx/.cache/pre-commit/repofxy8xq7j/py_env-python3.7/lib/python3.7/site-packages/cmake_format/__main__.py", line 117, in process_file
    parse_tree = parser.parse(tokens, parse_db)
  File "/Users/xx/.cache/pre-commit/repofxy8xq7j/py_env-python3.7/lib/python3.7/site-packages/cmake_format/parser.py", line 1180, in parse
    return consume_body(tokens, parse_db)
  File "/Users/xx/.cache/pre-commit/repofxy8xq7j/py_env-python3.7/lib/python3.7/site-packages/cmake_format/parser.py", line 1156, in consume_body
    subtree = consume_statement(tokens, parse_db)
  File "/Users/xx/.cache/pre-commit/repofxy8xq7j/py_env-python3.7/lib/python3.7/site-packages/cmake_format/parser.py", line 1026, in consume_statement
    repr(tokens[0].content)))
ValueError: Unexpected WORD token at 1:13, expecting l-paren, got 'hook'

**Comment by aharrison24** [comment] 2019-10-08 21:32
I think this is because you need a recent enough version of `pre-commit` (and more importantly the `identify` library that it depends upon). When I tested with the most recent version (I just did `pip3 install --upgrade pre-commit`) it seemed to work OK.

Out of interest, which version of pre-commit are you using?

**Comment by aharrison24** [comment] 2019-10-08 21:34
I'll try to work out the minimum version of `pre-commit` that is required and then enforce it in the `.pre-commit-hooks.yaml` file.

**Comment by qibint** [comment] 2019-10-08 21:38
My pre-commit version actually is 1.18.3 which is the latest and the cmake-format version 0.5.5.

**Comment by aharrison24** [comment] 2019-10-08 21:41
Yes, looks like pre-commit only requires identify>=1.0.0
https://github.com/pre-commit/pre-commit/blob/master/setup.cfg

But in fact you need identify >= 1.4.6
https://github.com/chriskuehl/identify/commit/5fb3a06daecf6409782190c02d5444c371031f53

It's possible to specify the minimum version of pre-commit, but not of identify.
https://github.com/pre-commit/pre-commit/pull/551#issuecomment-312535540

Not sure how to deal with this, other than by documenting the minimum version of `identify`?

**Comment by aharrison24** [comment] 2019-10-08 21:53
@qibint I've been trying to reproduce your issue by deliberately installing older versions of identify and pre-commit. For me the worst that happens is that pre-commit just skips changed files and doesn't run the linter on them. I've not seen it trying to run `cmake_lint` on non-cmake files.

**Comment by aharrison24** [comment] 2019-10-08 22:04
I've added a note to the README to run: `pip3 install "identify>=1.4.6"`
Does that solve the problem for you, or are you still seeing issues?

**Comment by qibint** [comment] 2019-10-09 02:35
@aharrison24 Sorry for the late reply. After upgrading identify lib to version 1.4.7, the issue still exists. 
I also clone the repo to my local directory and run in development mode using "pre-commit try-repo ./cmake-format-pre-commit cmake-format --verbose --files ./common/CMakeLists.txt", the dry run passed.
[cmake-format] cmake-format..............................................Passed


But whenever I use git commit to push, the printed error message is the same.
.....
.....
ValueError: Unexpected WORD token at 1:13, expecting l-paren, got 'hook'

**Comment by aharrison24** [comment] 2019-10-09 07:02
What about when you do a `pre-commit run --all` in the repo? Does that fail also?

And when you do a git commit, are you doing it from the CLI, or through a GUI? I'm just wondering if you've somehow got multiple versions of pre-commit installed (python 2 `pip` vs python 3 `pip3` for instance) and a different PATH env var in different circumstances. I've certainly had problems on MacOS when using Git GUIs launched from the dock, as they don't inherit the environment from `.bashrc` and friends (unless you launch them from the CLI).

Other than that, I'm clutching at straws. This feels like an issue that would need to be raised upstream with the pre-commit tool.

**Comment by aharrison24** [comment] 2019-10-16 21:53
I'm going to close this, as it appears to be an issue with pre-commit. Please feel free to re-open if you think there are any changes I can make in this repo which would fix the problem. Though ideally we'd continue using `types: [cmake]`, because that makes life much simpler than the alternative of having to manually list file patterns etc...

**Closed as completed by aharrison24** 2019-10-16 21:53 UTC
